version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # open-pull-requests-limit: 10
    # commit-message:
    #   prefix: "chore(deps)"
    # labels:
    #   - "dependencies"
    #   - "dependabot"
    # ignore:
    #   - dependency-name: "express"
    #     versions: ["^4.0.0"]